#version 450

struct Ocean
{
	vec2 H_y;
	vec2 H_x;
	vec2 H_z;
	vec2 Dx;
	vec2 Dz;
};

layout(std430, binding = 0) buffer H0Buffer
{
	Ocean H0Buffers[ ];
};

layout(std430, binding = 1) buffer HtBuffer 
{
	Ocean HtBuffers[ ];
};

layout(std430, binding = 2) buffer Ht_dmyBuffer 
{
	Ocean Ht_dmyBuffers[ ];
};

layout (std140, binding = 3) uniform UBO 
{
	float deltaT;
	float lamda;
	highp uint meshSize;
	highp uint OceanSizeLx;
	highp uint OceanSizeLz;
} ubo;

layout (local_size_x = 256) in;